apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver

# Note this is a patch file, so we only include the parts we want to change
spec:
  template:
    spec:
      containers:
        - name: webserver
          resources:
            limits:
              cpu: 330m
          env:
            - name: SOME_ENV_VAR
              value: Hello!
