apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/frontend
images:
  - name: frontend_placeholder
    newName: bencacr2025.azurecr.io/nanomon/frontend
    newTag: latest
