apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/data-api
  - ../../base/frontend
images:
  - name: data-api
    newName: basfkubewsacr.azurecr.io/smilr/data-api
    newTag: stable
  - name: frontend
    newName: basfkubewsacr.azurecr.io/smilr/frontend
    newTag: stable
