kind: Deployment
apiVersion: apps/v1

metadata:
  name: nanomon-runner

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanomon-runner
  template:
    metadata:
      labels:
        app: nanomon-runner
    spec:
      containers:
        - name: runner-container
          image: runner_placeholder
          imagePullPolicy: Always

          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 128Mi
