kind: Deployment
apiVersion: apps/v1

metadata:
  name: nanomon-runner

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanomon-runner
  template:
    metadata:
      labels:
        app: nanomon-runner
    spec:
      containers:
        - name: runner-container
          image: runner_placeholder
          imagePullPolicy: Always

          env:
            - name: POSTGRES_DSN
              value: "host=database user=nanomon dbname=nanomon sslmode=disable"
            - name: POSTGRES_DB
              value: "nanomon"
            - name: POSTGRES_USER
              value: "nanomon"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: password

          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 128Mi
