kind: Deployment
apiVersion: apps/v1

metadata:
  name: nanomon-frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanomon-frontend
  template:
    metadata:
      labels:
        app: nanomon-frontend
    spec:
      containers:
        - name: frontend-container

          image: {ACR_NAME}.azurecr.io/nanomon-frontend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8001

          env:
            - name: API_ENDPOINT
              value: http://{API_EXTERNAL_IP}/api
