kind: Deployment
apiVersion: apps/v1

metadata:
  name: nanomon-api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nanomon-api
      
  template:
    metadata:
      labels:
        app: nanomon-api

    spec:
      containers:
        - name: api-container

          image: {ACR_NAME}.azurecr.io/nanomon-api:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: POSTGRES_DSN
              value: "host={POSTGRES_POD_IP} user=nanomon dbname=nanomon sslmode=disable"
            - name: POSTGRES_PASSWORD
              value: "notVerySecret123!"