apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      
  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: {ACR_NAME}.azurecr.io/nanomon-postgres:latest

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: "nanomon"
            - name: POSTGRES_USER
              value: "nanomon"
            - name: POSTGRES_PASSWORD
              value: "notVerySecret123!"