apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/data-api
  - ../../base/frontend
images:
  - name: api
    newName: {EDIT_THIS_ACR_NAME}.azurecr.io/nanomon/api
    newTag: latest
  - name: frontend
    newName: {EDIT_THIS_ACR_NAME}.azurecr.io/nanomon/frontend
    newTag: latest
